from pydantic import BaseModel, Field


class PushKeys(BaseModel):
    """
    Encryption keys generated by the browser
    for the Push Subscription.
    """

    p256dh: str = Field(
        ...,
        min_length=1
    )

    auth: str = Field(
        ...,
        min_length=1
    )


class PushSubscription(BaseModel):
    """
    Push Subscription received from the browser.
    """

    endpoint: str = Field(..., min_length=1 )

    expirationTime: int | float | None = None

    keys: PushKeys